### ISSUE TITLE
unable to install "python bindings for bob"

### ISSUE THREAD

**Issue by ReleaseOnMonday** [code-player/user-authentication-using-voice-biometrics#3]
If you could mention specific packages as there are a whole lot of packages available related to bob

**Comment by ReleaseOnMonday** [comment]
apt-get install libboost-all-dev
**pip3 install bob**
pip3 install bob.extension
apt-get install libboost-all-dev
pip3 install bob.blitz
apt-get install libblitz0-dev
pip3 install bob.blitz
apt-get install cmake
pip3 install bob.core
pip3 install bob.sp
**pip3 install bob.ap**

As per my understanding, bold one's are used in code, Rest are dependencies for them. Any comments on this?

**Comment by rhythmize** [comment]
Yeah, the bold ones are only used. 
But others are required as dependencies for them
